apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-user
  namespace: nextcloud
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-user
    creationPolicy: Owner
  data:
  - secretKey: nextcloud-username
    remoteRef:
      key: secrets-v2/data/nextcloud
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: nextcloud-password
    remoteRef:
      key: secrets-v2/data/nextcloud
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
