apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-iot-io
  namespace: hassos
spec:
  secretName: cert-iot-io
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  commonName: "iot.cryogence.io"
  dnsNames:
  - "iot.cryogence.io"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-iot
  namespace: hassos
spec:
  headers:
    # prevent MIME-type sniffing
    contentTypeNosniff: true
    # clickjacking protection
    frameDeny: true
    contentSecurityPolicy: >-
      base-uri 'self';
      connect-src 'self';
      font-src 'self';
      form-action 'self';
      frame-ancestors 'none';
      frame-src 'none';
      img-src 'self' data:;
      manifest-src 'self';
      media-src 'self';
      object-src 'none';
      worker-src 'self';
      upgrade-insecure-requests
    # restrict browser features
    # set to (self) as needed.
    permissionsPolicy: >-
      accelerometer=(),
      bluetooth=(),
      camera=(),
      geolocation=(),
      gyroscope=(),
      interest-cohort=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      publickey-credentials-get=(),
      screen-wake-lock=(),
      serial=(),
      usb=(),
      vr=()
    # dont leak url paths to other origins
    referrerPolicy: strict-origin-when-cross-origin
    # hsts configs
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    # block bots
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow, noarchive, nosnippet, notranslate, noimageindex"
      Cross-Origin-Opener-Policy: "same-origin"
      Cross-Origin-Resource-Policy: "same-site"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hassos-webui
  namespace: hassos
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`iot.cryogence.io`)
      services:
        - name: hassos
          port: 8123
          scheme: http
      middlewares:
        - name: headers-iot
          namespace: hassos
  tls:
    secretName: cert-iot-io
