apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hassos-config
  namespace: hassos
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hassos-configuration
    creationPolicy: Owner
  data:
  - secretKey: configuration.yaml
    remoteRef:
      key: secrets-v2/data/hassos
      property: configuration
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
