apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ns.yml
  - resources/storageclass.yml
  - resources/ingress.yml
  - resources/snapshot.yml
  - resources/backup.yml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.7.1
    releaseName: "longhorn"
    namespace: longhorn-system
    includeCRDs: true
    valuesFile: values.yml
