defaultSettings:
  allowCollectingLonghornUsageMetrics: false
  storageReservedPercentageForDefaultDisk: 5
  defaultDataPath: "/var/lib/longhorn"
  #nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  v1DataEngine: false
  v2DataEngine: true
  v2DataEngineHugepageLimit: "1024"
  createDefaultDiskLabeledNodes: true
defaultBackupStore:
  backupTarget: "nfs://10.10.10.31:/mnt/zpool/ark/longhorn"
preUpgradeChecker:
  jobEnabled: false
# define our own storageclass
persistence:
  defaultClass: false
  dataEngine: v2
service:
  ui:
    type: ClusterIP
