defaultSettings:
  allowCollectingLonghornUsageMetrics: false
  storageReservedPercentageForDefaultDisk: 5
  defaultDataPath: "/var/mnt/longhorn"
  #nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
  v1DataEngine: true
  v2DataEngine: false
defaultBackupStore:
  backupTarget: "nfs://10.10.10.31:/mnt/zpool/ark/longhorn"
preUpgradeChecker:
  jobEnabled: false
# define our own storageclass
persistence:
  defaultClass: false
  dataEngine: v1
service:
  ui:
    type: ClusterIP
