apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music-nfs
spec:
  storageClassName: navidrome-music-nfs
  nfs:
    server: 10.10.10.31
    path: /mnt/zpool/ark/data/media/music
  mountOptions:
    - nfsvers=4
    - async
    - soft
    - nolock
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
