apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: naivdrome-secrets
  namespace: navidrome
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: navidrome-secrets
    creationPolicy: Owner
  data:
  - secretKey: navidrome-baseurl
    remoteRef:
      key: secrets-v2/data/navidrome
      property: baseurl
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: navidrome-spotify-id
    remoteRef:
      key: secrets-v2/data/navidrome
      property: spotify-id
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: navidrome-spotify-secret
    remoteRef:
      key: secrets-v2/data/navidrome
      property: spotify-secret
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: navidrome-lastfm-apikey
    remoteRef:
      key: secrets-v2/data/navidrome
      property: lastfm-apikey
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: navidrome-lastfm-secret
    remoteRef:
      key: secrets-v2/data/navidrome
      property: lastfm-secret
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
