apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wikijs-ess
  namespace: wikijs
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: wikijs-ess
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secrets-v2/data/wikijs
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: password
    remoteRef:
      key: secrets-v2/data/wikijs
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
