apiVersion: v1
kind: ConfigMap
metadata:
  name: snipeit-cm-env
  namespace: snipeit
data:
  # BASIC APP SETTINGS
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://sam.cryogence.io"
  APP_PORT: "8000"
  APP_TIMEZONE: "America/Los_Angeles"
  APP_LOCALE: "en-US"
  MAX_RESULTS: "500"
  # SECURITY HEADER SETTINGS
  APP_TRUSTED_PROXIES: "10.0.0.0/8"
  APP_ALLOW_INSECURE_HOSTS: "true"
  # DATABASE SETTINGS
  DB_CONNECTION: "mysql"
  DB_HOST: "mariadb.databases.svc.cluster.local"
  DB_PORT: "3306"
  DB_DATABASE: "snipeit"
  DB_PREFIX: "null"
  DB_DUMP_PATH: "/usr/bin"
  DB_CHARSET: "utf8mb4"
  DB_COLLATION: "utf8mb4_unicode_ci"
  # REDIS SETTINGS
  SESSION_DRIVER: "redis"
  CACHE_DRIVER: "redis"
  REDIS_HOST: "redis.snipeit.svc.cluster.local"
  REDIS_PORT: "6379"
  # OUTGOING MAIL SERVER SETTINGS
  MAIL_DRIVER: "log"
  # IMAGE LIBRARY
  IMAGE_LIB: "gd"
  # PHP UPLOAD LIMITS
  PHP_UPLOAD_LIMIT: "100"
  PHP_POST_MAX_SIZE: "100"
  PHP_UPLOAD_MAX_FILESIZE: "100"
  PHP_MEMORY_LIMIT: "100"
