apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snipeit-user
  namespace: snipeit
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: snipeit-user
    creationPolicy: Owner
  data:
  - secretKey: snipeit-username
    remoteRef:
      key: secrets-v2/data/snipeit
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: snipeit-password
    remoteRef:
      key: secrets-v2/data/snipeit
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: snipeit-appkey
    remoteRef:
      key: secrets-v2/data/snipeit
      property: app-key
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue

