apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions-pvc
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
  namespace: freshrss
  labels:
    app: freshrss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1.25.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
            - name: freshrss-extensions
              mountPath: /var/www/FreshRSS/extensions
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: freshrss-username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freshrss-password
                  key: password
            - name: OIDC_PROVIDER_METADATA_URL
              valueFrom:
                secretKeyRef:
                  name: freshrss-oidc
                  key: freshrss-metadata
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: freshrss-oidc
                  key: freshrss-clientid
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: freshrss-oidc
                  key: freshrss-clientsecret
            #- name: OIDC_CLIENT_CRYPTO_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: freshrss-oidc
            #      key: freshrss-cryptokey
          envFrom:
            - configMapRef:
                name: freshrss-cm-env
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 4
              memory: 4Gi
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
spec:
  selector:
    app: freshrss
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
