apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss-oidc
  namespace: freshrss
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: freshrss-oidc
    creationPolicy: Owner
  data:
  - secretKey: freshrss-metadata
    remoteRef:
      key: secrets-v2/data/freshrss-oidc
      property: metadata
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: freshrss-clientid
    remoteRef:
      key: secrets-v2/data/freshrss-oidc
      property: clientid
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: freshrss-clientsecret
    remoteRef:
      key: secrets-v2/data/freshrss-oidc
      property: clientsecret
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: freshrss-cryptokey
    remoteRef:
      key: secrets-v2/data/freshrss-oidc
      property: cryptokey
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
