apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # ignore status updates such as ExternalSecret refreshTime
  # which causes argocd to constantly sync.
  resource.customizations.ignoreResourceUpdates.all: |
    jsonPointers:
    - /status
