# apply this if you need access to the ui
# during initial setup
apiVersion: v1
kind: Service
metadata:
  name: argo-ui-temp
  namespace: argocd
  annotations: {"io.cilium/lb-ipam-ips": "10.10.10.112"}
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: https
    protocol: TCP
    targetPort: 8080
