apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-pvc
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: radarr-data-nfs
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: servarr
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.16.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-data
              mountPath: /data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 4
              memory: 4Gi
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: radarr-data
          persistentVolumeClaim:
            claimName: radarr-data-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: servarr
spec:
  selector:
    app: radarr
  ports:
    - name: http
      port: 7878
      protocol: TCP
      targetPort: 7878
  type: ClusterIP
