apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: prowlarr-data-nfs
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: servarr
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.30.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              name: http
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
            - name: prowlarr-data
              mountPath: /data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 4
              memory: 4Gi
      volumes:
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: servarr
spec:
  selector:
    app: prowlarr
  ports:
    - name: http
      port: 9696
      protocol: TCP
      targetPort: 9696
  type: ClusterIP
