apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonarr-data-nfs
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: servarr
  labels:
    app: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              name: http
              protocol: TCP
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-data
              mountPath: /data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 4
              memory: 4Gi
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: sonarr-data
          persistentVolumeClaim:
            claimName: sonarr-data-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: servarr
spec:
  selector:
    app: sonarr
  ports:
    - name: http
      port: 8989
      protocol: TCP
      targetPort: 8989
  type: ClusterIP
