apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-pvc
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lidarr-data-nfs
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: servarr
  labels:
    app: lidarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:2.9.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8686
              name: http
              protocol: TCP
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: lidarr-data
              mountPath: /data
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 6
              memory: 4Gi
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config-pvc
        - name: lidarr-data
          persistentVolumeClaim:
            claimName: lidarr-data-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: servarr
spec:
  selector:
    app: lidarr
  ports:
    - name: http
      port: 8686
      protocol: TCP
      targetPort: 8686
  type: ClusterIP
