apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-pvc
  namespace: servarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data-nfs
  namespace: servarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: transmission-data-nfs
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: servarr
  labels:
    app: transmission
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:4.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          volumeMounts:
            - name: transmission-config
              mountPath: /config
            - name: transmission-data
              mountPath: /data/torrents
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
            - name: TRANSMISSION_WEB_HOME
              value: "/flood-for-transmission/"
            - name: DOCKER_MODS
              value: "linuxserver/mods:transmission-floodui"
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 6
              memory: 6Gi
      volumes:
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config-pvc
        - name: transmission-data
          persistentVolumeClaim:
            claimName: transmission-data-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: servarr
spec:
  selector:
    app: transmission
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
  type: ClusterIP
