apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  storageClassName: jellyfin-media-nfs
  nfs:
    server: 10.10.10.31
    path: /mnt/zpool/ark/data/media
  mountOptions:
    - nfsvers=4
    - async
    - soft
    - nolock
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
