apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dbegin@protonmail.com
    privateKeySecretRef:
      name: le-staging
    solvers:
      - dns01:
          cloudflare:
            email: dbegin@protonmail.com
            apiTokenSecretRef:
              name: cloudflare-api
              key: cloudflare-api-key
        selector:
          dnsZones:
            - "cryogence.io"
