apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ns.yml
  #- resources/tlsoption.yml
  - resources/traefik.yml
  - resources/argocd-ingress.yml
  - resources/hubble-ingress.yml
  - external-services/adguard.yml
  - external-services/opnsense.yml
  - external-services/proxmox.yml
  - external-services/switch.yml
  - external-services/truenas.yml
  - external-services/truenas-backup.yml
  - external-services/vault.yml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 33.2.1
    releaseName: "traefik"
    namespace: traefik
    includeCRDs: true
    valuesFile: values.yml
