installCRDs: true
crds:
  createClusterExternalSecret: true
  createClusterSecretStore: true
  createSecretStore: true
vault:
  enableTokenCache: false
#resources:
#  requests:
#    cpu: 10m
#    memory: 32Mi
#  limits:
#    cpu: 2
#    memory: 1Gi
