apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - resources/ns.yml
  - resources/secret.yml
  - resources/ingress.yml

helmCharts:
  - name: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: 8.7.0
    releaseName: "nextcloud"
    namespace: nextcloud
    includeCRDs: true
    valuesFile: values.yml

# need to add namespace patch missing from templates:
# ref: https://github.com/nextcloud/helm/pull/792
patches:
  - target:
      kind: "^(ConfigMap|Service|PersistentVolumeClaim|Deployment)$"
      name: "^nextcloud.*$"
    patch: |-
      - op: add
        path: /metadata/namespace
        value: nextcloud
