global:
  nameOverride: "authentik"
  env:
    - name: AUTHENTIK_LOG_LEVEL
      value: "info"
    # force ipv4
    - name: AUTHENTIK_LISTEN__HTTP
      value: "0.0.0.0:9000"
    - name: AUTHENTIK_LISTEN__HTTPS
      value: "0.0.0.0:9443"
    - name: AUTHENTIK_LISTEN__METRICS
      value: "0.0.0.0:9300"
    - name: AUTHENTIK_LISTEN__LDAP
      value: "0.0.0.0:3389"
    - name: AUTHENTIK_LISTEN__LDAPS
      value: "0.0.0.0:6636"
    - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
      value: "127.0.0.0/8,10.0.0.0/8"
    # database configs
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: "postgres.databases.svc.cluster.local"
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: "authentik"
    # s3 configs
    - name: AUTHENTIK_STORAGE__BACKEND
      value: "s3"
    - name: AUTHENTIK_STORAGE__S3__BUCKET_NAME
      value: "authentik"
    - name: AUTHENTIK_STORAGE__S3__ENDPOINT
      value: "https://s3.cryogence.io"
    - name: AUTHENTIK_STORAGE__S3__CUSTOM_DOMAIN
      value: "s3.cryogence.io/authentik"
    # bootstrap secrets
    - name: AUTHENTIK_BOOTSTRAP_EMAIL
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-email
    - name: AUTHENTIK_BOOTSTRAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-password
    - name: AUTHENTIK_BOOTSTRAP_TOKEN
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-api-key
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-secret-key
    # email secrets
    - name: AUTHENTIK_EMAIL__USERNAME
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-email
    - name: AUTHENTIK_EMAIL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-email-token
    - name: AUTHENTIK_EMAIL__FROM
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-email
    # db secrets
    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-username
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-password
    # s3 secrets
    - name: AUTHENTIK_STORAGE__S3__ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-s3-access-key
    - name: AUTHENTIK_STORAGE__S3__SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-user
          key: authentik-s3-secret-key
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
email:
  host: "smtp.protonmail.ch"
  port: 587
  use_tls: true
  use_ssl: false
  timeout: 10
server:
  resources:
#    requests:
#      cpu: 100m
#      memory: 128Mi
    limits:
      cpu: 2
      memory: 2Gi
worker:
  resources:
#    requests:
#      cpu: 100m
#      memory: 128Mi
    limits:
      cpu: 2
      memory: 2Gi
#geoip:
#  resources:
#    requests:
#      cpu: 100m
#      memory: 128Mi
#    limits:
#      cpu: 2
#      memory: 1Gi
