apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb-user
  namespace: databases
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mariadb-user
    creationPolicy: Owner
  data:
  - secretKey: mariadb-username
    remoteRef:
      key: secrets-v2/data/mariadb
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: mariadb-password
    remoteRef:
      key: secrets-v2/data/mariadb
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
