apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-sql-io
  namespace: databases
spec:
  secretName: cert-sql-io
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  commonName: "sql.cryogence.io"
  dnsNames:
  - "sql.cryogence.io"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-sql
  namespace: databases
spec:
  headers:
    # prevent MIME-type sniffing
    contentTypeNosniff: true
    # clickjacking protection
    frameDeny: true
    contentSecurityPolicy: >-
      base-uri 'self';
      connect-src 'self';
      default-src 'self';
      font-src 'self' data:;
      form-action 'self';
      frame-ancestors 'none';
      frame-src 'none';
      img-src 'self' data: https://www.gravatar.com;
      manifest-src 'self';
      media-src 'self';
      object-src 'none';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      worker-src 'self';
      upgrade-insecure-requests
    # restrict browser features
    # set to (self) as needed.
    permissionsPolicy: >-
      accelerometer=(),
      bluetooth=(),
      camera=(),
      geolocation=(),
      gyroscope=(),
      interest-cohort=(),
      magnetometer=(),
      microphone=(),
      midi=(),
      payment=(),
      picture-in-picture=(),
      publickey-credentials-get=(),
      screen-wake-lock=(),
      serial=(),
      usb=(),
      vr=()
    # dont leak url paths to other origins
    referrerPolicy: strict-origin-when-cross-origin
    # hsts configs
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    # block bots
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow, noarchive, nosnippet, notranslate, noimageindex"
      Cross-Origin-Opener-Policy: "same-origin"
      Cross-Origin-Resource-Policy: "same-site"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin-webui
  namespace: databases
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sql.cryogence.io`)
      services:
        - name: pgadmin
          port: 80
          scheme: http
      middlewares:
        - name: headers-sql
          namespace: databases
  tls:
    secretName: cert-sql-io
