apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-oidc
  namespace: databases
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-oidc
    creationPolicy: Owner
  data:
  - secretKey: config_local.py
    remoteRef:
      key: secrets-v2/data/pgadmin-oidc
      property: config-local
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
