apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-user
  namespace: databases
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-user
    creationPolicy: Owner
  data:
  - secretKey: pgadmin-email
    remoteRef:
      key: secrets-v2/data/pgadmin
      property: email
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: pgadmin-password
    remoteRef:
      key: secrets-v2/data/pgadmin
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
