apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codeserver-oidc
  namespace: codeserver
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: codeserver-oidc
    creationPolicy: Owner
  data:
  - secretKey: codeserver-clientid
    remoteRef:
      key: secrets-v2/data/codeserver-oidc
      property: clientid
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: codeserver-client-secret
    remoteRef:
      key: secrets-v2/data/codeserver-oidc
      property: client-secret
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codeserver
  namespace: codeserver
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: codeserver
    creationPolicy: Owner
  data:
  - secretKey: codeserver-username
    remoteRef:
      key: secrets-v2/data/codeserver
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: codeserver-password
    remoteRef:
      key: secrets-v2/data/codeserver
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: codeserver-dburl
    remoteRef:
      key: secrets-v2/data/codeserver
      property: db_url
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
