apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: draw-pvc
  namespace: draw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draw
  namespace: draw
  labels:
    app: draw
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: draw
  template:
    metadata:
      labels:
        app: draw
    spec:
      containers:
        - name: draw
          image: excalidraw/excalidraw:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - name: draw
              mountPath: /opt/node_app/app/node_modules
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
      volumes:
        - name: draw
          persistentVolumeClaim:
            claimName: draw-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: draw
  namespace: draw
spec:
  selector:
    app: draw
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
