apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-init
  namespace: unifi
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: unifi-init
    creationPolicy: Owner
  data:
  - secretKey: initmongo.js
    remoteRef:
      key: secrets-v2/data/unifi-init
      property: mongoinit
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
