apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: unifi
  labels:
    app: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: tcp
              protocol: TCP
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: unifi-init
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
          #command: ["--wiredTigerCacheSizeGB 0.5"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1
              memory: 1Gi
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data-pvc
        - name: unifi-init
          secret:
            secretName: unifi-init
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: unifi
spec:
  selector:
    app: mongo
  ports:
    - name: tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
  type: ClusterIP
