apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: unifi-controller
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: lscr.io/linuxserver/unifi-network-application:8.6.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: dev-com
              protocol: TCP
            - containerPort: 3478
              name: stun
              protocol: UDP
            - containerPort: 1001
              name: discovery
              protocol: UDP
          volumeMounts:
            - name: unifi-config
              mountPath: /config
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: unifi-user
                  key: unifi-username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: unifi-user
                  key: unifi-password
          envFrom:
            - configMapRef:
                name: unifi-cm-env
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2
              memory: 1Gi
      volumes:
        - name: unifi-config
          persistentVolumeClaim:
            claimName: unifi-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  selector:
    app: unifi-controller
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-backend
  namespace: unifi
  annotations:
    "lbipam.cilium.io/ips": "10.10.10.101"
spec:
  selector:
    app: unifi-controller
  ports:
    - name: dev-com
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: discovery
      port: 1001
      protocol: UDP
      targetPort: 1001
  type: LoadBalancer
