apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-who-io
  namespace: whoami
spec:
  secretName: cert-who-io
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  commonName: "who.cryogence.io"
  dnsNames:
  - "who.cryogence.io"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-http
  namespace: whoami
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`who.cryogence.io`)
      services:
        - name: whoami
          port: 80
          scheme: http
  tls:
    secretName: cert-who-io
