replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 4
    memory: 4Gi
volumeMounts:
  - name: wikijs-data
    mountPath: /data
volumes:
  - name: wikijs-data
    persistentVolumeClaim:
      claimName: wikijs-data-pvc
postgresql:
  enabled: false
  postgresqlHost: postgres.databases.svc.cluster.local
  postgresqlDatabase: wikijs
  postgresqlPort: "5432"
  postgresqlUser: svcwikijs
  existingSecretKey: wikijs-ess
