apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  # snapshot hourly and retain last 6
  cron: "0 * * * *"
  task: "snapshot"
  groups:
  - default
  retain: 6
  concurrency: 2
  labels:
    type: 'snap'
    schedule: 'hourly'
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  # daily backup and retain weekly
  cron: "0 0 * * *"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 2
  labels:
    type: 'full'
    schedule: 'daily'
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-monthly
  namespace: longhorn-system
spec:
  # monthly backup and retain last 6
  cron: "0 3 1 * *"
  task: "backup"
  groups:
  - default
  retain: 6
  concurrency: 2
  labels:
    type: 'full'
    schedule: 'monthly'
