apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  # weekly backups retain monthly
  cron: "0 6 * * SUN"
  task: "backup"
  groups:
  - default
  retain: 4
  concurrency: 2
  labels:
    type: 'full'
    schedule: 'weekly'
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  # daily backups and retain weekly
  cron: "0 0 * * *"
  task: "backup"
  groups:
  - default
  retain: 7
  concurrency: 2
  labels:
    type: 'full'
    schedule: 'daily'
