apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-auth-io
  namespace: authentik
spec:
  secretName: cert-auth-io
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  commonName: "auth.cryogence.io"
  dnsNames:
  - "auth.cryogence.io"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-auth
  namespace: authentik
spec:
  headers:
    accessControlAllowMethods: ['GET', 'OPTIONS', 'PUT', 'POST', 'PATCH']
    accessControlMaxAge: 100
    browserXssFilter: true
    contentSecurityPolicy: "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https: data:; connect-src 'self' https:; frame-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-ancestors 'self'; base-uri 'self';"
    contentTypeNosniff: true
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
    customResponseHeaders:
      X-Robots-Tag: none,noarchive,nosnippet,notranslate,noimageindex
    permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    forceSTSHeader: true
    frameDeny: true
    sslRedirect: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    referrerPolicy: no-referrer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-webui
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.cryogence.io`)
      services:
        - name: authentik-server
          port: 80
          scheme: http
      middlewares:
        - name: headers-auth
          namespace: authentik
  tls:
    secretName: cert-auth-io
