apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-user
  namespace: authentik
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-user
    creationPolicy: Owner
  data:
  - secretKey: authentik-username
    remoteRef:
      key: secrets-v2/data/authentik
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: authentik-email
    remoteRef:
      key: secrets-v2/data/authentik
      property: email
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: authentik-password
    remoteRef:
      key: secrets-v2/data/authentik
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: authentik-api-key
    remoteRef:
      key: secrets-v2/data/authentik
      property: api_key
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
