apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport

resources:
  #- resources/ns.yml
  #- resources/secret.yml
  #- resources/ingress.yml

helmCharts:
  - name: teleport
    repo: https://charts.releases.teleport.dev
    version: 16
    releaseName: "teleport"
    namespace: teleport
    includeCRDs: true
    valuesFile: values.yml
