apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-user
  namespace: vaultwarden
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-user
    creationPolicy: Owner
  data:
  - secretKey: vaultwarden-username
    remoteRef:
      key: secrets-v2/data/vaultwarden
      property: username
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: vaultwarden-password
    remoteRef:
      key: secrets-v2/data/vaultwarden
      property: password
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
  - secretKey: vaultwarden-dburl
    remoteRef:
      key: secrets-v2/data/vaultwarden
      property: db_url
      conversionStrategy: Default #argo sync issue
      decodingStrategy: None #argo sync issue
      metadataPolicy: None #argo sync issue
