crds:
  enabled: true
  keep: true
replicaCount: 1
extraArgs:
  - --dns01-recursive-nameservers=10.10.10.1:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 10.10.10.1
#resources:
#  requests:
#    cpu: 100m
#    memory: 64Mi
#  limits:
#    cpu: 2
#    memory: 1Gi
