apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: servarr
  namespace: argocd
  labels:
    name: apps
  annotations:
    argocd.argoproj.io/sync-wave: '1110'
spec:
  project: production
  source:
    path: servarr
    repoURL: https://git.cryogence.net/cryogence/k8s-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: servarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        maxDuration: 16m
        factor: 2
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - ApplyOutOfSyncOnly=true
    - RespectIgnoreDifferences=true
